# Generated by Anaconda 34.25.7.6
# Generated by pykickstart v3.32
#version=RHEL9
# Use graphical install
graphical
repo --name="AppStream" --baseurl=file:///run/install/sources/mount-0000-cdrom/AppStream

%addon com_redhat_kdump --enable --reserve-mb='auto'

%end

# Keyboard layouts
keyboard --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=ens192 --ipv6=auto --activate
network  --hostname=SRV-GIT-U-APP-K8S-Worker-001

# Use CDROM installation media
cdrom

%packages
@^server-product-environment

%end

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.6.0
ignoredisk --only-use=sda
autopart
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone Asia/Yangon --utc

#Root password
rootpw --lock
user --groups=wheel --name=imsadmin --password=$6$QO2ih5hSM/euRi97$mAyHtOhNURFGBFx95Z94jDo7jHUu.5s5MvLhig2ivtYy0BPWsTJnlcAf7NReecxADs211kyCLZKkwuAdBWph91 --iscrypted --gecos="imsadmin"
